#!/bin/sh

### BEGIN INIT INFO
# Provides:          ajenti
# Required-Start:    $network $syslog $local_fs
# Required-Stop:     $network $syslog $local_fs
# Should-Start:      $local_fs
# Should-Stop:       $local_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Ajenti
# Description:       Ajenti administration frontend
### END INIT INFO

# Source function library
. /etc/init.d/functions

#the service name, a python script
SNAME=Ajenti

#the full path and name of the daemon program
#Warning: The name of executable file must be identical with service name
PROG=$(which ajenti-panel)


# start function
start() {
    #check the daemon status first
    if [ -f /var/lock/subsys/$SNAME ]
    then
        echo "$SNAME is already started!"
        exit 0;
    else
        echo $"Starting $SNAME ..."
        python $PROG &
        [ $? -eq 0 ] && touch /var/lock/subsys/$SNAME
        echo $"$SNAME started."
        exit 0;
    fi
}

#stop function
stop() {
    echo "Stopping $SNAME ..."
    pid=`ps -ef | grep '[p]ython $PROG' | awk '{ print $2 }'`
    [ "$pid"X != "X" ] && kill $pid
    rm -rf /var/lock/subsys/$SNAME
}

case "$1" in
start)
  start
  ;;
stop)
  stop
  ;;
reload|restart)
  stop
  start
  ;;
status)
  pid=`ps -ef | grep '[p]ython $PROG' | awk '{ print $2 }'`
  if [ "$pid"X = "X" ]; then
      echo "$SNAME is stoped."
  else
      echo "$SNAME (pid $pid) is running..."
  fi
  ;;
*)
  echo $"\nUsage: $0 {start|stop|restart|status}"
  exit 1
esac
